param([ValidateSet('passive','capacity','exercise','virtualization')][string]$Mode='passive')
$ErrorActionPreference='Continue'
$results=[ordered]@{schema='windows-environment-capability-census/v2';timestamp=(Get-Date).ToUniversalTime().ToString('o');mode=$Mode;runner=[ordered]@{};capacity=[ordered]@{};hardware=[ordered]@{};capabilities=@()}
function Add-Cap($name,$advertised,$installed,$callable,$exercised,$oracle,$qualification,$reason){$results.capabilities += [ordered]@{capability=$name;advertised=$advertised;installed=$installed;callable=$callable;exercised=$exercised;oracleSatisfied=$oracle;qualification=$qualification;reason=$reason}}
function Safe($sb){try{&$sb}catch{$null}}
$results.runner.os=[Environment]::OSVersion.VersionString;$results.runner.arch=[Runtime.InteropServices.RuntimeInformation]::OSArchitecture.ToString();$results.runner.processArch=[Runtime.InteropServices.RuntimeInformation]::ProcessArchitecture.ToString();$results.runner.user=$env:USERNAME;$results.runner.session=$env:SESSIONNAME;$results.runner.imageOS=$env:ImageOS;$results.runner.imageVersion=$env:ImageVersion
$admin=([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator);$results.runner.administrator=$admin
$cs=Get-CimInstance Win32_ComputerSystem;$cpus=@(Get-CimInstance Win32_Processor);$cpu=$cpus|Select-Object -First 1
$results.runner.hypervisorPresent=$cs.HypervisorPresent;$results.runner.vmMonitorModeExtensions=$cpu.VMMonitorModeExtensions;$results.runner.virtualizationFirmwareEnabled=$cpu.VirtualizationFirmwareEnabled;$results.runner.secondLevelAddressTranslationExtensions=$cpu.SecondLevelAddressTranslationExtensions
$results.capacity.cpu=[ordered]@{name=$cpu.Name;manufacturer=$cpu.Manufacturer;logicalProcessors=($cpus|Measure-Object NumberOfLogicalProcessors -Sum).Sum;cores=($cpus|Measure-Object NumberOfCores -Sum).Sum;maxClockMHz=$cpu.MaxClockSpeed}
$os=Get-CimInstance Win32_OperatingSystem;$results.capacity.memory=[ordered]@{physicalBytes=[int64]$cs.TotalPhysicalMemory;freePhysicalBytes=[int64]$os.FreePhysicalMemory*1KB;totalVirtualBytes=[int64]$os.TotalVirtualMemorySize*1KB;freeVirtualBytes=[int64]$os.FreeVirtualMemory*1KB}
$results.capacity.volumes=@(Get-Volume -ErrorAction SilentlyContinue|Where-Object DriveLetter|ForEach-Object{[ordered]@{drive="$($_.DriveLetter):";filesystem=$_.FileSystem;sizeBytes=[int64]$_.Size;freeBytes=[int64]$_.SizeRemaining}})
$results.hardware.display=@(Get-CimInstance Win32_VideoController -ErrorAction SilentlyContinue|Select-Object Name,AdapterCompatibility,AdapterRAM,DriverVersion)
$results.hardware.network=@(Get-CimInstance Win32_NetworkAdapter -ErrorAction SilentlyContinue|Where-Object PhysicalAdapter|Select-Object Name,Manufacturer,MACAddress,Speed,NetConnectionStatus)
$results.hardware.disks=@(Get-CimInstance Win32_DiskDrive -ErrorAction SilentlyContinue|Select-Object Model,InterfaceType,MediaType,Size)
$results.hardware.controllers=@(Get-PnpDevice -PresentOnly -ErrorAction SilentlyContinue|Where-Object Class -in @('SCSIAdapter','HDC','Net','Display','System','HIDClass','USB','MEDIA')|Select-Object -First 120 Class,FriendlyName,InstanceId,Status)
$results.hardware.tpm=Safe {Get-Tpm|Select-Object TpmPresent,TpmReady,TpmEnabled,TpmActivated,ManufacturerIdTxt}
$features=@('Microsoft-Hyper-V-All','VirtualMachinePlatform','Containers','Microsoft-Windows-Subsystem-Linux');foreach($f in $features){$x=Get-WindowsOptionalFeature -Online -FeatureName $f -ErrorAction SilentlyContinue;Add-Cap "windows-feature:$f" ($null-ne$x) ($x.State-eq'Enabled') ($null-ne$x) $false $false 'observed' $(if($x){$x.State}else{'not-found'})}
foreach($cmd in @('docker','wsl','Get-VM','New-VHD','Mount-VHD','New-VMSwitch','New-NetNat','WinAppDriver.exe','msiexec.exe')){$c=Get-Command $cmd -ErrorAction SilentlyContinue;Add-Cap "command:$cmd" ($null-ne$c) ($null-ne$c) ($null-ne$c) $false $false 'observed' $(if($c){$c.Source}else{'not-found'})}
foreach($svc in @('vmms','vmcompute','hns','docker')){$s=Get-Service $svc -ErrorAction SilentlyContinue;Add-Cap "service:$svc" ($null-ne$s) ($null-ne$s) ($null-ne$s) $false $false 'observed' $(if($s){$s.Status.ToString()}else{'not-found'})}
if($Mode -eq 'capacity'){
 $sw=[Diagnostics.Stopwatch]::StartNew();$h=[Security.Cryptography.SHA256]::Create();$buf=New-Object byte[] (8MB);for($i=0;$i-lt64;$i++){$null=$h.ComputeHash($buf)};$sw.Stop();$results.capacity.cpuProbe=[ordered]@{bytes=512MB;seconds=$sw.Elapsed.TotalSeconds;note='bounded SHA256 work-rate observation, not benchmark'}
 $path=Join-Path $env:RUNNER_TEMP 'capacity-probe.bin';$buf=New-Object byte[] (8MB);$sw.Restart();$fs=[IO.File]::Open($path,[IO.FileMode]::Create,[IO.FileAccess]::Write,[IO.FileShare]::None);for($i=0;$i-lt32;$i++){$fs.Write($buf,0,$buf.Length)};$fs.Flush($true);$fs.Dispose();$sw.Stop();$results.capacity.diskWriteProbe=[ordered]@{bytes=256MB;seconds=$sw.Elapsed.TotalSeconds;freeAfterBytes=(Get-Item $path).PSDrive.Free;note='bounded sequential write observation'};Remove-Item $path -Force
}
if($Mode -eq 'exercise'){
 $d=Get-Command docker -ErrorAction SilentlyContinue;if($d){$v=& docker version --format '{{json .}}' 2>&1;$ok=$LASTEXITCODE-eq0;Add-Cap 'docker-daemon' $true $true $true $true $ok $(if($ok){'exercised'}else{'unavailable'}) ($v|Out-String).Trim()}
 $w=Get-Command wsl -ErrorAction SilentlyContinue;if($w){$v=(& wsl --status 2>&1|Out-String).Trim();$code=$LASTEXITCODE;$global:LASTEXITCODE=0;Add-Cap 'wsl-runtime' $true $true $true $true ($code-eq0) $(if($code-eq0){'exercised'}else{'unavailable'}) $v}
 try{$p=Start-Process notepad.exe -PassThru;Start-Sleep 2;$wins=Get-Process -Id $p.Id -ErrorAction Stop;$ok=$wins.MainWindowHandle-ne0;Add-Cap 'interactive-top-level-window' $true $true $true $true $ok $(if($ok){'exercised'}else{'unavailable'}) "hwnd=$($wins.MainWindowHandle);session=$($wins.SessionId)";$p|Stop-Process -Force}catch{Add-Cap 'interactive-top-level-window' $true $true $false $true $false 'unavailable' $_.Exception.Message}
 try{$vhd=Join-Path $env:RUNNER_TEMP 'cap-probe.vhdx';New-VHD -Path $vhd -Dynamic -SizeBytes 256MB -ErrorAction Stop|Out-Null;$disk=Mount-VHD -Path $vhd -PassThru -ErrorAction Stop|Get-Disk;Initialize-Disk $disk.Number -PartitionStyle GPT -ErrorAction Stop;$part=New-Partition -DiskNumber $disk.Number -UseMaximumSize -AssignDriveLetter;Format-Volume -Partition $part -FileSystem NTFS -Confirm:$false|Out-Null;$drive="$($part.DriveLetter):\";$nonce=[guid]::NewGuid().ToString();Set-Content (Join-Path $drive 'nonce.txt') $nonce;$read=(Get-Content (Join-Path $drive 'nonce.txt'));Dismount-VHD $vhd;Add-Cap 'vhd-lifecycle' $true $true $true $true ($read-eq$nonce) 'exercised' 'create/mount/format/write/read/unmount';Remove-Item $vhd -Force -ErrorAction SilentlyContinue}catch{Add-Cap 'vhd-lifecycle' $true $false $false $true $false 'unavailable' $_.Exception.Message}
}
if($Mode -eq 'virtualization'){
 try{$vmms=Get-Service vmms -ErrorAction Stop;$can=Get-Command New-VM -ErrorAction Stop;$name='cap-'+[guid]::NewGuid().ToString('N').Substring(0,8);$vhd=Join-Path $env:RUNNER_TEMP "$name.vhdx";New-VHD $vhd -Dynamic -SizeBytes 256MB|Out-Null;$vm=New-VM -Name $name -Generation 2 -MemoryStartupBytes 512MB -VHDPath $vhd -NoVHD:$false -ErrorAction Stop;Add-Cap 'hyperv-control-plane' $true $true $true $true ($null-ne$vm) 'exercised' "created=$name;vmms=$($vmms.Status)";Remove-VM $name -Force -ErrorAction SilentlyContinue;Remove-Item $vhd -Force -ErrorAction SilentlyContinue}catch{Add-Cap 'hyperv-control-plane' $true $false $false $true $false 'unavailable' $_.Exception.Message}
}
$out=Join-Path $env:RUNNER_TEMP "windows-capability-$Mode-$($results.runner.arch).json";$results|ConvertTo-Json -Depth 9|Set-Content -Encoding UTF8 $out;Write-Host "CAPABILITY_RECEIPT=$out";Get-Content $out
