param([ValidateSet('passive','exercise','virtualization')][string]$Mode='passive')
$ErrorActionPreference='Continue'
$results=[ordered]@{schema='windows-environment-capability-census/v1';timestamp=(Get-Date).ToUniversalTime().ToString('o');mode=$Mode;runner=[ordered]@{};capabilities=@()}
function Add-Cap($name,$advertised,$installed,$callable,$exercised,$oracle,$qualification,$reason){$results.capabilities += [ordered]@{capability=$name;advertised=$advertised;installed=$installed;callable=$callable;exercised=$exercised;oracleSatisfied=$oracle;qualification=$qualification;reason=$reason}}
$results.runner.os=[Environment]::OSVersion.VersionString;$results.runner.arch=[Runtime.InteropServices.RuntimeInformation]::OSArchitecture.ToString();$results.runner.processArch=[Runtime.InteropServices.RuntimeInformation]::ProcessArchitecture.ToString();$results.runner.user=$env:USERNAME;$results.runner.session=$env:SESSIONNAME;$results.runner.imageOS=$env:ImageOS;$results.runner.imageVersion=$env:ImageVersion
$admin=([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator);$results.runner.administrator=$admin
$cs=Get-CimInstance Win32_ComputerSystem;$cpu=Get-CimInstance Win32_Processor | Select-Object -First 1;$results.runner.hypervisorPresent=$cs.HypervisorPresent;$results.runner.vmMonitorModeExtensions=$cpu.VMMonitorModeExtensions;$results.runner.virtualizationFirmwareEnabled=$cpu.VirtualizationFirmwareEnabled;$results.runner.secondLevelAddressTranslationExtensions=$cpu.SecondLevelAddressTranslationExtensions
$features=@('Microsoft-Hyper-V-All','VirtualMachinePlatform','Containers','Microsoft-Windows-Subsystem-Linux');foreach($f in $features){$x=Get-WindowsOptionalFeature -Online -FeatureName $f -ErrorAction SilentlyContinue;Add-Cap "windows-feature:$f" ($null-ne$x) ($x.State-eq'Enabled') ($null-ne$x) $false $false 'observed' $(if($x){$x.State}else{'not-found'})}
foreach($cmd in @('docker','wsl','Get-VM','New-VHD','Mount-VHD','WinAppDriver.exe','msiexec.exe')){$c=Get-Command $cmd -ErrorAction SilentlyContinue;Add-Cap "command:$cmd" ($null-ne$c) ($null-ne$c) ($null-ne$c) $false $false 'observed' $(if($c){$c.Source}else{'not-found'})}
foreach($svc in @('vmms','vmcompute','hns','docker')){$s=Get-Service $svc -ErrorAction SilentlyContinue;Add-Cap "service:$svc" ($null-ne$s) ($null-ne$s) ($null-ne$s) $false $false 'observed' $(if($s){$s.Status.ToString()}else{'not-found'})}
if($Mode -ne 'passive'){
  $d=Get-Command docker -ErrorAction SilentlyContinue;if($d){$v=& docker version --format '{{json .}}' 2>&1;$ok=$LASTEXITCODE-eq0;Add-Cap 'docker-daemon' $true $true $true $true $ok $(if($ok){'exercised'}else{'unavailable'}) ($v|Out-String).Trim()}
  $w=Get-Command wsl -ErrorAction SilentlyContinue;if($w){$v=& wsl --status 2>&1;$ok=$LASTEXITCODE-eq0;Add-Cap 'wsl-runtime' $true $true $true $true $ok $(if($ok){'exercised'}else{'unavailable'}) ($v|Out-String).Trim()}
  try{$p=Start-Process notepad.exe -PassThru;Start-Sleep 2;$wins=Get-Process -Id $p.Id -ErrorAction Stop;$ok=$wins.MainWindowHandle-ne0;Add-Cap 'interactive-top-level-window' $true $true $true $true $ok $(if($ok){'exercised'}else{'unavailable'}) "hwnd=$($wins.MainWindowHandle);session=$($wins.SessionId)";$p|Stop-Process -Force}catch{Add-Cap 'interactive-top-level-window' $true $true $false $true $false 'unavailable' $_.Exception.Message}
  try{$vhd=Join-Path $env:RUNNER_TEMP 'cap-probe.vhdx';New-VHD -Path $vhd -Dynamic -SizeBytes 64MB -ErrorAction Stop|Out-Null;Add-Cap 'vhd-create' $true $true $true $true (Test-Path $vhd) 'exercised' $vhd;Remove-Item $vhd -Force -ErrorAction SilentlyContinue}catch{Add-Cap 'vhd-create' $true $false $false $true $false 'unavailable' $_.Exception.Message}
}
if($Mode -eq 'virtualization'){
  try{$vmms=Get-Service vmms -ErrorAction Stop;$can=Get-Command New-VM -ErrorAction Stop;Add-Cap 'hyperv-control-plane' $true $true $true $true ($vmms.Status-eq'Running') $(if($vmms.Status-eq'Running'){'exercised'}else{'unavailable'}) "vmms=$($vmms.Status); New-VM=$($can.Source)"}catch{Add-Cap 'hyperv-control-plane' $false $false $false $true $false 'unavailable' $_.Exception.Message}
}
$out=Join-Path $env:RUNNER_TEMP "windows-capability-$Mode-$($results.runner.arch).json";$results|ConvertTo-Json -Depth 8|Set-Content -Encoding UTF8 $out;Write-Host "CAPABILITY_RECEIPT=$out";Get-Content $out